### ISSUE TITLE
Path to sprite

### ISSUE THREAD

**Issue by ghost** [jonathantneal/postcss-svg#1]
It works finally, thank you so much!
But the documentation should be more clear about the path is relative to Gulpfile. Most Frontend Developers use naturally the Document root, that won't work. It took some time to find it out :)

It would be nice if we could use a path in CSS:
```css
li {
  background: url(relative-path-to-file/symbols.svg#arrow-right) no-repeat;
}
```
