### ISSUE TITLE
SVG Parameters don't work 

### ISSUE THREAD

**Issue by ghost** [jonathantneal/postcss-svg#2]
I have the following SVG Sprite (created and optimized with gulp-svg-sprites):
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0" style="position:absolute">
  <symbol id="minus" viewBox="0 0 48 48">
    <path stroke="var(--color,#144a81)" stroke-width="var(--strokewidth,2px)" d="M0 24h48"></path>
  </symbol>

  <symbol id="plus" viewBox="0 0 48 48">
    <g stroke="var(--color,#144a81)" stroke-width="var(--strokewidth,2px)"><path d="M0 24h48M24 0v48"></path></g>
  </symbol>
</svg>
```

Stylesheet:
```css
li::before {
  position: absolute;
  top: 3px;
  left: -33px;
  width: 22px;
  height: 22px;
  content: '';
  background: url("symbols.svg#plus" param(--color red) param(--strokewidth 3px)) no-repeat;
  background-size: contain;
  background-position: center;
}
```

Result:
SVG has only the default color and the passed parameters not rendered
```css
  background: url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 48 48' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 24h48M24 0v48' stroke='var%28--color%2C%23144a81%29' stroke-width='var%28--strokewidth%2C2px%29'/%3E%3C/svg%3E") no-repeat;
```
