### ISSUE TITLE
Colour / fill not getting encoded

### ISSUE THREAD

**Issue by saltcod** [jonathantneal/postcss-svg#3]
Salut friend!   Finally switching away from the old plugin to this one! 

Everything seems to be working except the encoding of the colour / fill.  Input and output in the screens below.  Not sure if this is expected behaviour or not? Or if there's any way around? 

We do thank you sire! 

![2017-11-15 at 12 34 pm](https://user-images.githubusercontent.com/105593/32846290-6e6e0762-ca01-11e7-8b74-5b4ed3703cc5.png)
![2017-11-15 at 12 30 pm](https://user-images.githubusercontent.com/105593/32846291-6e80a548-ca01-11e7-8eec-c06c511be130.png)

**Comment by jonathantneal** [comment]
Hey @saltcod, it’s always nice to see a familiar face.

The old plugin did things very oddly; it read specific sibling declarations in the rule — things like `fill` — and wrote them into the SVG. That functionality does not exist in postcss-svg.

This plugin follows the [SVG Parameters](https://tabatkins.github.io/specs/svg-params/) standard. Now, we can pass in CSS variables to your SVG.

---

Imagine the following (totally valid) SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <symbol id="square">
    <rect style="fill:var(--color,black)" width="100%" height="100%"/>
  </symbol>
</svg>
```

[SVG Parameters](https://tabatkins.github.io/specs/svg-params/) dictate that we can pass a default value to `--color` using `param()`:

```css
.icon--square {
  content: url("path/to/sprite.svg#square" param(--color blue));
}
```

Which means the SVG is interpreted as if it was written this way all along:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <symbol id="square">
    <rect style="fill:blue" width="100%" height="100%"/>
  </symbol>
</svg>
```

And it will compile like this:

```css
.icon--square {
  content: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Crect style='fill:blue' width='100%25' height='100%25'/%3E%3C/svg%3E");
}
```

---

Now, had we not passed any params into the SVG, like this:

```css
.icon--square {
  content: url("path/to/sprite.svg#square");
}
```

Then the SVG would have been interpreted as if it was written this way all along:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <symbol id="square">
    <rect style="fill:black" width="100%" height="100%"/>
  </symbol>
</svg>
```

---

Does this make sense? Let me know if you have any other questions. I’m only closing the issue because your specific problem does not relate to this plugin, but I’ll happily answer any followups you have. 😄
